CREATE TABLE IF NOT EXISTS b_airecogn_result
(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ACTIVITY_ID INT UNSIGNED NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'pending',
    SUMMARY TEXT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PROCESSED_AT DATETIME NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UX_AIRECOGN_RESULT_ACTIVITY (ACTIVITY_ID),
    KEY IX_AIRECOGN_RESULT_STATUS (STATUS)
);

